const Map<String, String> appUrPk = {
  'Settings': 'سیٹنگز',
  'Customize how KistBook looks and which language the app uses.':
      'KistBook کی شکل اور ایپ کی زبان یہاں سے تبدیل کریں۔',
  'Appearance': 'ظاہری انداز',
  'Language': 'زبان',
  'Choose the theme that feels best for your team.':
      'اپنی ٹیم کے لیے مناسب تھیم منتخب کریں۔',
  'Pick the language for the full application experience.':
      'پورے ایپ تجربے کے لیے زبان منتخب کریں۔',
  'System': 'سسٹم',
  'Light': 'لائٹ',
  'Dark': 'ڈارک',
  'Use device setting': 'ڈیوائس کی سیٹنگ استعمال کریں',
  'Always use the light theme': 'ہمیشہ لائٹ تھیم استعمال کریں',
  'Always use the dark theme': 'ہمیشہ ڈارک تھیم استعمال کریں',
  'Application theme': 'ایپلیکیشن تھیم',
  'App language': 'ایپ کی زبان',
  'Current selection': 'موجودہ انتخاب',
  'Welcome Back': 'دوبارہ خوش آمدید',
  'Sign in with your phone number and password to continue to KistBook.':
      'KistBook جاری رکھنے کے لیے فون نمبر اور پاس ورڈ سے لاگ اِن کریں۔',
  'Phone Number': 'فون نمبر',
  'Password': 'پاس ورڈ',
  'Enter password': 'پاس ورڈ درج کریں',
  'Remember me': 'مجھے یاد رکھیں',
  'Forgot Password?': 'پاس ورڈ بھول گئے؟',
  'Please contact the owner to reset your password.':
      'پاس ورڈ ری سیٹ کرنے کے لیے اونر سے رابطہ کریں۔',
  'or': 'یا',
  'Create Owner Account': 'اونر اکاؤنٹ بنائیں',
  'Create the first owner account. This user will have full access and can assign other users later.':
      'KistBook مینیج کرنے، رسائی کنٹرول کرنے اور بعد میں ٹیم ممبرز شامل کرنے کے لیے بنیادی اونر اکاؤنٹ بنائیں۔',
  'First Name': 'پہلا نام',
  'Enter first name': 'پہلا نام درج کریں',
  'Last Name': 'آخری نام',
  'Enter last name': 'آخری نام درج کریں',
  'Confirm Password': 'پاس ورڈ کی تصدیق',
  'Re-enter password': 'دوبارہ پاس ورڈ درج کریں',
  'Create Owner': 'اونر بنائیں',
  'By continuing, you agree to our ': 'جاری رکھنے سے آپ ہماری ',
  'Terms of Service': 'شرائطِ استعمال',
  ' and ': ' اور ',
  'Privacy Policy': 'پرائیویسی پالیسی',
  'Phone number is required.': 'فون نمبر لازمی ہے۔',
  'Phone number must be 11 digits.': 'فون نمبر 11 ہندسوں کا ہونا چاہیے۔',
  'Password is required.': 'پاس ورڈ لازمی ہے۔',
  'Login Failed': 'لاگ اِن ناکام',
  'Invalid phone number or password.': 'فون نمبر یا پاس ورڈ غلط ہے۔',
  'First name is required.': 'پہلا نام لازمی ہے۔',
  'Last name is required.': 'آخری نام لازمی ہے۔',
  'Password should be at least 6 characters.':
      'پاس ورڈ کم از کم 6 حروف کا ہونا چاہیے۔',
  'Password and confirm password must match.':
      'پاس ورڈ اور تصدیقی پاس ورڈ ایک جیسے ہونے چاہئیں۔',
  'Registration Failed': 'رجسٹریشن ناکام',
  'This phone number is already in use.': 'یہ فون نمبر پہلے سے استعمال میں ہے۔',
  'Owner account already exists. Please login or ask the owner to add users.':
      'اونر اکاؤنٹ پہلے سے موجود ہے۔ براہ کرم لاگ اِن کریں یا اونر سے صارف شامل کرنے کو کہیں۔',
  'Dashboard': 'ڈیش بورڈ',
  'Customers': 'کسٹمرز',
  'Products': 'پروڈکٹس',
  'Installments': 'اقساط',
  'Daily Collection': 'یومیہ وصولی',
  'Payments': 'ادائیگیاں',
  'Reports': 'رپورٹس',
  'Workspace': 'ورک اسپیس',
  'Manage customers, installments, and reports':
      'کسٹمرز، اقساط اور رپورٹس کو ایک جگہ سے مینیج کریں۔',
  'Installment operations for modern micro business teams':
      'جدید چھوٹے کاروباری ٹیموں کے لیے قسطی آپریشنز۔',
  'Keep the app open at midnight to auto-generate the daily due report in offline mode.':
      'آف لائن موڈ میں روزانہ کی ڈیو رپورٹ خودکار بنانے کے لیے ایپ کو آدھی رات تک کھلا رکھیں۔',
  'Switch to light mode': 'لائٹ موڈ پر جائیں',
  'Switch to dark mode': 'ڈارک موڈ پر جائیں',
  'Switch theme': 'تھیم تبدیل کریں',
  'Business Overview': 'کاروباری جائزہ',
  'Monitor collections, pending dues, and customer activity in one place.':
      'وصولی، بقایا جات اور کسٹمر سرگرمی ایک جگہ دیکھیں۔',
  'Outstanding': 'بقایا',
  'Collected': 'وصول شدہ',
  'Pending Today': 'آج بقایا',
  '@count items': '@count آئٹمز',
  'Registered profiles': 'رجسٹرڈ پروفائلز',
  'Installments due today': 'آج واجب الادا اقساط',
  'Overdue': 'اوورڈیو',
  'Missed or delayed entries': 'مس یا تاخیر شدہ اندراجات',
  'Tracked receipts only': 'صرف ٹریک شدہ رسیٹس',
  'Today Alerts': 'آج کے الرٹس',
  '@count active': '@count فعال',
  'No installments due today.': 'آج کوئی قسط واجب الادا نہیں ہے۔',
  'Daily PDF Report': 'روزانہ PDF رپورٹ',
  'Report Generated': 'رپورٹ تیار ہوگئی',
  'Generate report': 'رپورٹ بنائیں',
  'No dashboard data available.': 'ڈیش بورڈ کے لیے کوئی ڈیٹا موجود نہیں۔',
  'Tracking Only': 'صرف ٹریکنگ',
  'Payments are tracking-only. No gateway is connected.':
      'ادائیگیاں صرف ٹریک ہوتی ہیں، کوئی گیٹ وے منسلک نہیں ہے۔',
  'Pending Collection': 'بقایا وصولی',
  'Record': 'ریکارڈ',
  'Manual entry': 'مینول اندراج',
  'Reports Saved': 'رپورٹس محفوظ ہوگئیں',
  'Daily Due Installment PDF': 'روزانہ واجب الادا اقساط PDF',
  'Report Saved': 'رپورٹ محفوظ ہوگئی',
  'Generate today report': 'آج کی رپورٹ بنائیں',
  'Record Payment': 'ادائیگی ریکارڈ کریں',
  'Remaining: @amount': 'باقی: @amount',
  'Amount': 'رقم',
  'Enter received amount': 'موصولہ رقم درج کریں',
  'Note': 'نوٹ',
  'Add payment note': 'ادائیگی کا نوٹ شامل کریں',
  'Payment date': 'ادائیگی کی تاریخ',
  'Save Payment': 'ادائیگی محفوظ کریں',
  'Add Customer': 'کسٹمر شامل کریں',
  'Edit Customer': 'کسٹمر میں ترمیم',
  'Customer name': 'کسٹمر کا نام',
  'Enter customer full name': 'کسٹمر کا پورا نام درج کریں',
  'Phone': 'فون',
  'CNIC': 'شناختی کارڈ',
  'Address': 'پتہ',
  'Street, area, city': 'گلی، علاقہ، شہر',
  'Reference / referred by': 'حوالہ / ریفر کیا گیا بذریعہ',
  'Enter reference person name': 'حوالہ دینے والے شخص کا نام درج کریں',
  'Customer name is required.': 'کسٹمر کا نام لازمی ہے۔',
  'Address is required.': 'پتہ لازمی ہے۔',
  'Validation Errors': 'توثیقی غلطیاں',
  'Save Customer': 'کسٹمر محفوظ کریں',
  'Direct Customer': 'ڈائریکٹ کسٹمر',
  'Edit': 'ترمیم',
  'Delete': 'حذف کریں',
  'Customer Detail': 'کسٹمر کی تفصیل',
  'Customer profile and installment activity': 'کسٹمر پروفائل اور قسطی سرگرمی',
  'Not provided': 'فراہم نہیں کیا گیا',
  'Reference': 'حوالہ',
  'Add Installment Plan': 'قسطی پلان شامل کریں',
  'Manage Plans': 'پلان مینیج کریں',
  'History': 'ہسٹری',
  'Plans & History': 'پلان اور ہسٹری',
  'All Products': 'تمام پروڈکٹس',
  'No plan history found for selected filters.':
      'منتخب فلٹرز کے لیے کوئی پلان ہسٹری نہیں ملی۔',
  'Refreshing plan details from server...':
      'سرور سے پلان کی تفصیل تازہ کی جا رہی ہے...',
  'Loading customer plan details...': 'کسٹمر پلان کی تفصیل لوڈ ہو رہی ہے...',
  'Unable to refresh plan details. Showing saved local data.':
      'پلان کی تفصیل تازہ نہیں ہو سکی۔ محفوظ لوکل ڈیٹا دکھایا جا رہا ہے۔',
  'Retry': 'دوبارہ کوشش',
  'Customer not found': 'کسٹمر نہیں ملا',
  'Customer Payment Detail': 'کسٹمر ادائیگی کی تفصیل',
  'No previous plan': 'کوئی پچھلا پلان نہیں',
  'New customer': 'نیا کسٹمر',
  '@percent on-time': '@percent وقت پر',
  'Rating @rating': 'ریٹنگ @rating',
  'Running plans': 'چلتے ہوئے پلان',
  'Completed': 'مکمل',
  'Late installments': 'تاخیر شدہ اقساط',
  'Paid on time': 'وقت پر ادا شدہ',
  'Last payment': 'آخری ادائیگی',
  'No payment yet': 'ابھی کوئی ادائیگی نہیں',
  'Plan Summary': 'پلان کا خلاصہ',
  'Total plans': 'کل پلان',
  'Total payments': 'کل ادائیگیاں',
  'Collected amount': 'وصول شدہ رقم',
  'Outstanding amount': 'بقایا رقم',
  'Recent Plans': 'حالیہ پلان',
  'Installment @amount • Every @days days': 'قسط @amount • ہر @days دن بعد',
  'New': 'نیا',
  'Excellent': 'بہترین',
  'Good': 'اچھا',
  'Average': 'اوسط',
  'Risky': 'خطرناک',
  '@count running': '@count جاری',
  '@count completed': '@count مکمل',
  'Add Product': 'پروڈکٹ شامل کریں',
  'Edit Product': 'پروڈکٹ میں ترمیم',
  'Product': 'پروڈکٹ',
  'Brand name': 'برانڈ کا نام',
  'Enter brand name': 'برانڈ کا نام درج کریں',
  'Product name': 'پروڈکٹ کا نام',
  'Enter product title': 'پروڈکٹ کا عنوان درج کریں',
  'SKU / code': 'SKU / کوڈ',
  'Sale price': 'فروخت قیمت',
  'Notes': 'نوٹس',
  'Optional product notes': 'اختیاری پروڈکٹ نوٹس',
  'Product Images': 'پروڈکٹ تصاویر',
  'Add Product Images': 'پروڈکٹ تصاویر شامل کریں',
  'Choose from Gallery': 'گیلری سے منتخب کریں',
  'Select multiple product images': 'متعدد پروڈکٹ تصاویر منتخب کریں',
  'Take Photo': 'تصویر بنائیں',
  'Capture a product image': 'پروڈکٹ کی تصویر بنائیں',
  'Remove Image?': 'تصویر ہٹائیں؟',
  'Are you sure you want to remove this product image?':
      'کیا آپ واقعی یہ پروڈکٹ تصویر ہٹانا چاہتے ہیں؟',
  'Remove': 'ہٹائیں',
  'Image Selection Failed': 'تصویر منتخب نہیں ہو سکی',
  'Unable to add product images. Please try again.':
      'پروڈکٹ تصاویر شامل نہیں ہو سکیں۔ براہ کرم دوبارہ کوشش کریں۔',
  'Close': 'بند کریں',
  'Brand name is required.': 'برانڈ کا نام لازمی ہے۔',
  'Product name is required.': 'پروڈکٹ کا نام لازمی ہے۔',
  'Price must be greater than zero.': 'قیمت صفر سے زیادہ ہونی چاہیے۔',
  'Product name should be at least 2 characters.':
      'پروڈکٹ کا نام کم از کم 2 حروف پر مشتمل ہونا چاہیے۔',
  'Brand name should be at least 2 characters.':
      'برانڈ کا نام کم از کم 2 حروف پر مشتمل ہونا چاہیے۔',
  'SKU/code should be at least 3 characters if provided.':
      'اگر SKU/کوڈ دیا جائے تو کم از کم 3 حروف کا ہونا چاہیے۔',
  'Price looks too high. Please recheck the amount.':
      'قیمت بہت زیادہ لگ رہی ہے، براہ کرم رقم دوبارہ چیک کریں۔',
  'Notes should be 250 characters or less.':
      'نوٹس 250 حروف یا اس سے کم ہونے چاہئیں۔',
  'Save Product': 'پروڈکٹ محفوظ کریں',
  'Product Detail': 'پروڈکٹ کی تفصیل',
  'Product profile and latest pricing details':
      'پروڈکٹ پروفائل اور تازہ ترین قیمت کی تفصیل',
  'Brand': 'برانڈ',
  'SKU': 'SKU',
  'Current price': 'موجودہ قیمت',
  'Last updated': 'آخری اپڈیٹ',
  'Price History': 'قیمت کی ہسٹری',
  'No price history found.': 'قیمت کی کوئی ہسٹری نہیں ملی۔',
  'Initial price recorded': 'ابتدائی قیمت ریکارڈ کی گئی',
  'Updated from @amount': '@amount سے اپڈیٹ کی گئی',
  'Plan Detail': 'پلان کی تفصیل',
  'Edit plans': 'پلان میں ترمیم',
  '@count product plans linked': '@count پروڈکٹ پلان منسلک',
  'All Product Plans': 'تمام پروڈکٹ پلان',
  'No plans found for this customer.': 'اس کسٹمر کے لیے کوئی پلان نہیں ملا۔',
  'SKU: Not provided': 'SKU: فراہم نہیں کیا گیا',
  'SKU: @sku': 'SKU: @sku',
  'Quantity': 'تعداد',
  'Total': 'کل',
  'Deposit': 'ایڈوانس',
  'Installment': 'قسط',
  'Remaining': 'باقی',
  'Next due': 'اگلی واجب الادا',
  'N/A': 'دستیاب نہیں',
  'Frequency': 'وقفہ',
  '@days days': '@days دن',
  'Start date': 'آغاز کی تاریخ',
  'Current Plan Schedule': 'موجودہ پلان شیڈول',
  'Installment #@number': 'قسط نمبر @number',
  'Due: @date\nAmount: @amount • Remaining: @remaining':
      'تاریخ: @date\nرقم: @amount • باقی: @remaining',
  'Plan Updated': 'پلان اپڈیٹ ہوگیا',
  'Plan details have been refreshed.': 'پلان کی تفصیل تازہ کردی گئی ہے۔',
  'No installment plans available.': 'کوئی قسطی پلان دستیاب نہیں۔',
  'New Plan': 'نیا پلان',
  'Next due: @date': 'اگلی تاریخ: @date',
  '@count remaining': '@count باقی',
  'Paid': 'ادا شدہ',
  'Pending': 'زیر التوا',
  'Daily Installment': 'روزانہ قسط',
  '@count kist due': '@count قسط واجب الادا',
  'Yes': 'جی ہاں',
  '@name installment moved to @date.':
      '@name کی قسط @date پر منتقل کر دی گئی ہے۔',
  'Single Day Collection': 'ایک دن کی وصولی',
  'Selected date ke customers, product name, installment amount aur collection action yahan show hotay hain.':
      'منتخب تاریخ کے کسٹمرز، پروڈکٹ نام، قسطی رقم اور وصولی ایکشن یہاں دکھائے جاتے ہیں۔',
  'Today': 'آج',
  'Selected date': 'منتخب تاریخ',
  'Customers due': 'واجب الادا کسٹمرز',
  'Total collectible': 'کل قابل وصول',
  'Is date par koi kist due nahi mili.':
      'اس تاریخ پر کوئی قسط واجب الادا نہیں ملی۔',
  'Collect Installment': 'قسط وصول کریں',
  'Enter amount': 'رقم درج کریں',
  'Cancel': 'منسوخ کریں',
  'Save': 'محفوظ کریں',
  'Invalid Amount': 'غلط رقم',
  'Please enter a valid installment amount.':
      'براہ کرم درست قسطی رقم درج کریں۔',
  'Installment Collected': 'قسط وصول ہوگئی',
  '@name se @amount receive mark kar di gayi hai.':
      '@name سے @amount وصول شدہ کے طور پر محفوظ کردی گئی ہے۔',
  'Notice': 'اطلاع',
  'Daily due report generated at @path':
      'روزانہ واجب الادا رپورٹ @path پر تیار ہوگئی ہے۔',
  'Please review the detail below.': 'براہ کرم نیچے دی گئی تفصیل دیکھیں۔',
  'Please review the following @count items.':
      'براہ کرم درج ذیل @count آئٹمز دیکھیں۔',
  'Search @label': '@label تلاش کریں',
  'Select Customer': 'کسٹمر منتخب کریں',
  'No results found': 'کوئی نتیجہ نہیں ملا',
  'No customer selected': 'کوئی کسٹمر منتخب نہیں ہوا',
  'Daily Due Installments': 'روزانہ واجب الادا اقساط',
  'Date: @date': 'تاریخ: @date',
  'No installments are due today.': 'آج کوئی قسط واجب الادا نہیں۔',
  'Customer': 'کسٹمر',
  'Item': 'آئٹم',
  'Payable': 'قابل ادا',
};
