const Map<String, String> appEnUs = {
  'Settings': 'Settings',
  'Customize how KistBook looks and which language the app uses.':
      'Customize how KistBook looks and which language the app uses.',
  'Appearance': 'Appearance',
  'Language': 'Language',
  'Choose the theme that feels best for your team.':
      'Choose the theme that feels best for your team.',
  'Pick the language for the full application experience.':
      'Pick the language for the full application experience.',
  'System': 'System',
  'Light': 'Light',
  'Dark': 'Dark',
  'Use device setting': 'Use device setting',
  'Always use the light theme': 'Always use the light theme',
  'Always use the dark theme': 'Always use the dark theme',
  'Application theme': 'Application theme',
  'App language': 'App language',
  'Current selection': 'Current selection',
  'Dashboard': 'Dashboard',
  'Customers': 'Customers',
  'Products': 'Products',
  'Installments': 'Installments',
  'Daily Collection': 'Daily Collection',
  'Payments': 'Payments',
  'Reports': 'Reports',
  'Workspace': 'Workspace',
  'Manage customers, installments, and reports':
      'Manage customers, installments, and reports',
  'Installment operations for modern micro business teams':
      'Installment operations for modern micro business teams',
  'Keep the app open at midnight to auto-generate the daily due report in offline mode.':
      'Keep the app open at midnight to auto-generate the daily due report in offline mode.',
  'Switch to light mode': 'Switch to light mode',
  'Switch to dark mode': 'Switch to dark mode',
  'Switch theme': 'Switch theme',
  'Business Overview': 'Business Overview',
  'Monitor collections, pending dues, and customer activity in one place.':
      'Monitor collections, pending dues, and customer activity in one place.',
  'Outstanding': 'Outstanding',
  'Collected': 'Collected',
  'Pending Today': 'Pending Today',
  '@count items': '@count items',
  'Registered profiles': 'Registered profiles',
  'Installments due today': 'Installments due today',
  'Overdue': 'Overdue',
  'Missed or delayed entries': 'Missed or delayed entries',
  'Tracked receipts only': 'Tracked receipts only',
  'Today Alerts': 'Today Alerts',
  '@count active': '@count active',
  'No installments due today.': 'No installments due today.',
  'Daily PDF Report': 'Daily PDF Report',
  'Report Generated': 'Report Generated',
  'Generate report': 'Generate report',
  'No dashboard data available.': 'No dashboard data available.',
  'Tracking Only': 'Tracking Only',
  'Payments are tracking-only. No gateway is connected.':
      'Payments are tracking-only. No gateway is connected.',
  'Pending Collection': 'Pending Collection',
  'Record': 'Record',
  'Manual entry': 'Manual entry',
  'Reports Saved': 'Reports Saved',
  'Daily Due Installment PDF': 'Daily Due Installment PDF',
  'Report Saved': 'Report Saved',
  'Generate today report': 'Generate today report',
  'Record Payment': 'Record Payment',
  'Remaining: @amount': 'Remaining: @amount',
  'Amount': 'Amount',
  'Enter received amount': 'Enter received amount',
  'Note': 'Note',
  'Add payment note': 'Add payment note',
  'Payment date': 'Payment date',
  'Save Payment': 'Save Payment',
  'Add Customer': 'Add Customer',
  'Edit Customer': 'Edit Customer',
  'Customer name': 'Customer name',
  'Enter customer full name': 'Enter customer full name',
  'Phone': 'Phone',
  'CNIC': 'CNIC',
  'Address': 'Address',
  'Street, area, city': 'Street, area, city',
  'Reference / referred by': 'Reference / referred by',
  'Enter reference person name': 'Enter reference person name',
  'Customer name is required.': 'Customer name is required.',
  'Address is required.': 'Address is required.',
  'Validation Errors': 'Validation Errors',
  'Save Customer': 'Save Customer',
  'Direct Customer': 'Direct Customer',
  'Edit': 'Edit',
  'Delete': 'Delete',
  'Customer Detail': 'Customer Detail',
  'Customer profile and installment activity':
      'Customer profile and installment activity',
  'Not provided': 'Not provided',
  'Reference': 'Reference',
  'Add Installment Plan': 'Add Installment Plan',
  'Manage Plans': 'Manage Plans',
  'History': 'History',
  'Customer not found': 'Customer not found',
  'Customer Payment Detail': 'Customer Payment Detail',
  'No previous plan': 'No previous plan',
  'New customer': 'New customer',
  '@percent on-time': '@percent on-time',
  'Rating @rating': 'Rating @rating',
  'Running plans': 'Running plans',
  'Completed': 'Completed',
  'Late installments': 'Late installments',
  'Paid on time': 'Paid on time',
  'Last payment': 'Last payment',
  'No payment yet': 'No payment yet',
  'Plan Summary': 'Plan Summary',
  'Total plans': 'Total plans',
  'Total payments': 'Total payments',
  'Collected amount': 'Collected amount',
  'Outstanding amount': 'Outstanding amount',
  'Recent Plans': 'Recent Plans',
  'Installment @amount • Every @days days':
      'Installment @amount • Every @days days',
  'New': 'New',
  'Excellent': 'Excellent',
  'Good': 'Good',
  'Average': 'Average',
  'Risky': 'Risky',
  '@count running': '@count running',
  '@count completed': '@count completed',
  'Add Product': 'Add Product',
  'Edit Product': 'Edit Product',
  'Brand name': 'Brand name',
  'Enter brand name': 'Enter brand name',
  'Product name': 'Product name',
  'Enter product title': 'Enter product title',
  'SKU / code': 'SKU / code',
  'Sale price': 'Sale price',
  'Notes': 'Notes',
  'Optional product notes': 'Optional product notes',
  'Product Images': 'Product Images',
  'Add Product Images': 'Add Product Images',
  'Choose from Gallery': 'Choose from Gallery',
  'Select multiple product images': 'Select multiple product images',
  'Take Photo': 'Take Photo',
  'Capture a product image': 'Capture a product image',
  'Remove Image?': 'Remove Image?',
  'Are you sure you want to remove this product image?':
      'Are you sure you want to remove this product image?',
  'Remove': 'Remove',
  'Image Selection Failed': 'Image Selection Failed',
  'Unable to add product images. Please try again.':
      'Unable to add product images. Please try again.',
  'Close': 'Close',
  'Brand name is required.': 'Brand name is required.',
  'Product name is required.': 'Product name is required.',
  'Price must be greater than zero.': 'Price must be greater than zero.',
  'Product name should be at least 2 characters.':
      'Product name should be at least 2 characters.',
  'Brand name should be at least 2 characters.':
      'Brand name should be at least 2 characters.',
  'SKU/code should be at least 3 characters if provided.':
      'SKU/code should be at least 3 characters if provided.',
  'Price looks too high. Please recheck the amount.':
      'Price looks too high. Please recheck the amount.',
  'Notes should be 250 characters or less.':
      'Notes should be 250 characters or less.',
  'Save Product': 'Save Product',
  'Product Detail': 'Product Detail',
  'Product profile and latest pricing details':
      'Product profile and latest pricing details',
  'Brand': 'Brand',
  'SKU': 'SKU',
  'Current price': 'Current price',
  'Last updated': 'Last updated',
  'Price History': 'Price History',
  'No price history found.': 'No price history found.',
  'Initial price recorded': 'Initial price recorded',
  'Updated from @amount': 'Updated from @amount',
  'Plan Detail': 'Plan Detail',
  'Edit plans': 'Edit plans',
  '@count product plans linked': '@count product plans linked',
  'All Product Plans': 'All Product Plans',
  'No plans found for this customer.': 'No plans found for this customer.',
  'SKU: Not provided': 'SKU: Not provided',
  'SKU: @sku': 'SKU: @sku',
  'Quantity': 'Quantity',
  'Total': 'Total',
  'Deposit': 'Deposit',
  'Installment': 'Installment',
  'Remaining': 'Remaining',
  'Next due': 'Next due',
  'N/A': 'N/A',
  'Frequency': 'Frequency',
  '@days days': '@days days',
  'Start date': 'Start date',
  'Current Plan Schedule': 'Current Plan Schedule',
  'Installment #@number': 'Installment #@number',
  'Due: @date\nAmount: @amount • Remaining: @remaining':
      'Due: @date\nAmount: @amount • Remaining: @remaining',
  'Plan Updated': 'Plan Updated',
  'Plan details have been refreshed.': 'Plan details have been refreshed.',
  'No installment plans available.': 'No installment plans available.',
  'New Plan': 'New Plan',
  'Next due: @date': 'Next due: @date',
  '@count remaining': '@count remaining',
  'Paid': 'Paid',
  'Pending': 'Pending',
  'Daily Installment': 'Daily Installment',
  '@count kist due': '@count kist due',
  'Yes': 'Yes',
  '@name installment moved to @date.': '@name installment moved to @date.',
  'Single Day Collection': 'Single Day Collection',
  'Selected date ke customers, product name, installment amount aur collection action yahan show hotay hain.':
      'Customers, product names, installment amounts, and collection actions for the selected date appear here.',
  'Today': 'Today',
  'Selected date': 'Selected date',
  'Customers due': 'Customers due',
  'Total collectible': 'Total collectible',
  'Is date par koi kist due nahi mili.':
      'No installments are due on this date.',
  'Collect Installment': 'Collect Installment',
  'Enter amount': 'Enter amount',
  'Cancel': 'Cancel',
  'Save': 'Save',
  'Invalid Amount': 'Invalid Amount',
  'Please enter a valid installment amount.':
      'Please enter a valid installment amount.',
  'Installment Collected': 'Installment Collected',
  '@name se @amount receive mark kar di gayi hai.':
      '@amount has been recorded as collected from @name.',
  'Notice': 'Notice',
  'Daily due report generated at @path': 'Daily due report generated at @path',
  'Please review the detail below.': 'Please review the detail below.',
  'Please review the following @count items.':
      'Please review the following @count items.',
  'Search @label': 'Search @label',
  'Select Customer': 'Select Customer',
  'No results found': 'No results found',
  'No customer selected': 'No customer selected',
  'Daily Due Installments': 'Daily Due Installments',
  'Date: @date': 'Date: @date',
  'No installments are due today.': 'No installments are due today.',
  'Customer': 'Customer',
  'Item': 'Item',
  'Payable': 'Payable',
};
